// @formatter:off
////////////////////////////////////////////////////////////////////////////
//                         Kellen Siczka - 2082880                        //
//                        DePaul University - 24/25                       //
//              SE350 - Object-Oriented Software Development              //
//                ksiczka@depaul.edu | edu@kellensiczka.com               //
//         Eclipse Adoptium JRE 21.0.5.11 - Win11/WSL2 - MS VSCode        //
//           Completed by Kellen Siczka unless otherwise noted            //
//        Note: Docstrings and explanations may be generated by AI        //
////////////////////////////////////////////////////////////////////////////
//                         Week 7 - Spring Quarter                        //
//                          Lab 8 - Due 05-12-2025                        //
//            File Info: #16/17 | PrintError.java | Java Class            //
////////////////////////////////////////////////////////////////////////////
// @formatter:on

package dpu.se350.assignment2;

/**
 * Represents an action that prints an error message. Used when an error occurs during user input
 * processing.
 */
public class PrintError implements Action {
    private Dungeon dungeon;
    private Exception error;

    /**
     * Creates a new PrintError action.
     *
     * @param dungeon The dungeon
     * @param error The exception that occurred
     */
    public PrintError(Dungeon dungeon, Exception error) {
        this.dungeon = dungeon;
        this.error = error;
    }

    /**
     * Executes the action, printing the error message.
     */
    @Override
    public void execute() {
        System.out.println("Error: " + error.getMessage());
        System.out.println("Please try again.");
        System.exit(1);
    }

    /**
     * Returns a string representation of this action.
     *
     * @return A string representation of this action
     */
    @Override
    public String toString() {
        return "Print Error: " + error.getClass().getSimpleName();
    }
}
