// @formatter:off
////////////////////////////////////////////////////////////////////////////
//                         Kellen Siczka - 2082880                        //
//                        DePaul University - 24/25                       //
//              SE350 - Object-Oriented Software Development              //
//                ksiczka@depaul.edu | edu@kellensiczka.com               //
//         Eclipse Adoptium JRE 21.0.5.11 - Win11/WSL2 - MS VSCode        //
//           Completed by Kellen Siczka unless otherwise noted            //
//        Note: Docstrings and explanations may be generated by AI        //
////////////////////////////////////////////////////////////////////////////
//                         Week 7 - Spring Quarter                        //
//                          Lab 8 - Due 05-12-2025                        //
//              File Info: #9/17 | Warrior.java | Java Class              //
////////////////////////////////////////////////////////////////////////////
// @formatter:on

package dpu.se350.assignment2;

/**
 * Represents a Warrior character that specializes in strength rather than craft.
 */
public class Warrior extends Character {

    /**
     * Creates a new Warrior with the specified name. Warriors start with high strength (4), low
     * craft (1), and high health (15).
     *
     * @param name The warrior's name
     */
    public Warrior(String name) {
        super(name, 4, 1, 15);
    }
}
