// @formatter:off
////////////////////////////////////////////////////////////////////////////
//                         Kellen Siczka - 2082880                        //
//                        DePaul University - 24/25                       //
//              SE350 - Object-Oriented Software Development              //
//                ksiczka@depaul.edu | edu@kellensiczka.com               //
//         Eclipse Adoptium JRE 21.0.5.11 - Win11/WSL2 - MS VSCode        //
//           Completed by Kellen Siczka unless otherwise noted            //
//        Note: Docstrings and explanations may be generated by AI        //
////////////////////////////////////////////////////////////////////////////
//                         Week 7 - Spring Quarter                        //
//                          Lab 8 - Due 05-12-2025                        //
//              File Info: #8/17 | Wizard.java | Java Class               //
////////////////////////////////////////////////////////////////////////////
// @formatter:on

package dpu.se350.assignment2;

/**
 * Represents a Wizard character that specializes in craft rather than strength.
 */
public class Wizard extends Character {

    /**
     * Creates a new Wizard with the specified name. Wizards start with low strength (1), high craft
     * (4), and medium health (10).
     *
     * @param name The wizard's name
     */
    public Wizard(String name) {
        super(name, 1, 4, 10);
    }
}
